Repository TEAM-TRAVIS/TRAVIS-BACK, pull requests merged in 2023-07, with the labels that each got.

#3 Feature: userModel 생성
  travis/.eslintrc.json
  travis/app.js
  travis/config.env
  travis/models/userModel.js
  travis/package-lock.json
  travis/package.json
  travis/server
Labels: feature

#4 Feature: user db update
  .gitignore
  travis/app.js
  travis/models/userModel.js
  travis/routes/userRouter.js
  travis/server
Labels: feature

#8 Fix: docker db연결 해결
  travis/controllers/userController.js
  travis/models/userModel.js
  travis/server
Labels: bug

#9 feature: login/logout
  travis/.dockerignore
  travis/.eslintrc.json
  travis/app.js
  travis/controllers/mainController.js
  travis/controllers/userController.js
  travis/models/userModel.js
  travis/package-lock.json
  travis/package.json
  travis/routes/index.js
  travis/routes/mainRouter.js
  travis/routes/userRouter.js
  travis/server
  travis/views/login.ejs
  travis/views/main.ejs
Labels: feature

#11 refactor: login error, error code 302 -> 401
  travis/models/userModel.js
  travis/routes/userRouter.js
Labels: bug, enhancement

#12 Feature: update login security using Passport & JWT
  travis/app.js
  travis/config/passport.js
  travis/controllers/mainController.js
  travis/controllers/userController.js
  travis/package-lock.json
  travis/package.json
  travis/routes/mainRouter.js
  travis/routes/userRouter.js
Labels: feature
